type OrderForm {
  orderFormId: String
  value: Float
  items: [OrderFormItem]
}

type OrderFormItem {
  detailUrl: String
  imageUrl: String
  skuName: String
  price: String
  quantity: Float
}

input OrderFormItemInput {
  id: Int,
  index: Int,
  quantity: Int,
  seller: Int,
}

type IgnoreProfileInput {
    expectedOrderFormSections: [String],
    ignoreProfileData: Boolean
}

type OrderFormAddress {
    expectedOrderFormSections: [String],
    postalCode: String,
    country: String,
    addressType: String,
    receiverName: String,
    city: String,
    state: String,
    street: String,
    number: String,
    neighborhood: String
}

type OrderFormProfileInput {
    expectedOrderFormSections: [String],
    email: String
}