type OrderForm {
  orderFormId: String
  value: Float
  items: [OrderFormItem]
}

type OrderFormItem {
  detailUrl: String
  imageUrl: String
  skuName: String
  price: String
  quantity: Float
}

input OrderFormItemInput {
  id: Int,
  index: Int,
  quantity: Int,
  seller: Int,
}

input OrderFormAddressInput {
    addressType: String,
    postalCode: String,
    country: String,
    addressType: String,
    receiverName: String,
    city: String,
    state: String,
    street: String,
    number: String,
    complement: String,
    neighborhood: String
}

input OrderFormPaymentInput {
    paymentSystem: Int,
    referenceValue: Float,
    bin: Int,
    tokenId: String
}

input OrderFormProfileInput {
    email: String,
    isCorporate: Boolean,
    corporateDocument: String,
    corporateName: String,
    corporatePhone: String,
    document: String,
    documentType: String,
    firstName: String,
    lastName: String,
    phone: String,
    stateInscription: String,
    tradeName: String
}

input OrderFormPaymentTokenInput {
  tokenId: String,
  cardNumber: String,
  bin: String,
  paymentSystem: String,
  paymentSystemName: String
}
