type Product {
  brand: String
  categoryId: ID
  categories: [String]
  categoriesIds: [String]
  clusterHighlights: [ClusterHighlight] @resolve
  description: String
  items: [SKU]
  link: String
  linkText: String
  productId: ID
  productName: String
  properties: [Property] @resolve
  propertyGroups: [String] @resolve
  productReference: String
  recommendations: Recommendation @resolve
}

type ClusterHighlight {
  id: ID
  name: String
}

type Seller {
  sellerId: ID
  sellerName: String
  addToCartLink: String
  sellerDefault: Boolean
  commertialOffer: Offer
}

type Recommendation {
  buy: [Product]
  view: [Product]
}

type SKU {
  itemId: ID
  name: String
  nameComplete: String
  complementName: String
  ean: String
  referenceId: [Reference]
  measurementUnit: String
  unitMultiplier: Float
  images: [Image]
  sellers: [Seller]
  variations: [Property] @resolve
  attachments: [Attachment]
}

type Attachment {
  id: ID
  name: String
  required: Boolean
  domainValues: [DomainValues] @resolve
}

type DomainValues {
  FieldName: String
  MaxCaracters: String
  DomainValues: String
}

type Offer {
  Installments: [Installment]
  Price: Float
  ListPrice: Float
  PriceWithoutDiscount: Float
  RewardValue: Float
  PriceValidUntil: String
  AvailableQuantity: Float
  Tax: Float
  CacheVersionUsedToCallCheckout: String

  # TODO
  # DeliverySlaSamplesPerRegion
  # DeliverySlaSamples
  # DiscountHighlight
  # GiftSkuIds
  # Teasers
  # BuyTogether
}

type Image {
  imageId: ID
  imageLabel: String
  imageTag: String
  imageUrl: String
  imageText: String
}

type Property {
  name: String
  values: [String]
}

type Installment {
  Value: Float
  InterestRate: Float
  TotalValuePlusInterestRate: Float
  NumberOfInstallments: Int
  PaymentSystemName: String
  PaymentSystemGroupName: String
  Name: String
}

type Reference {
  Key: String
  Value: String
}
