const orderForm = {
  orderFormId: '473a630cbab44de78fdd29ec6799e829',
  salesChannel: '1',
  loggedIn: false,
  isCheckedIn: false,
  storeId: null,
  checkedInPickupPointId: null,
  allowManualPrice: false,
  canEditData: true,
  userProfileId: null,
  userType: null,
  ignoreProfileData: false,
  value: 159400,
  messages: [],
  items: [
    {
      uniqueId: '9AF34EF0ED8843F2AD404F69177B30F8',
      id: '20',
      productId: '9',
      productRefId: '',
      refId: '9812983',
      ean: '9812983',
      name: 'Top Everyday Necessaire 100 RMS',
      skuName: '100 RMS',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2020-12-17T14:27:07.4191263Z',
      tax: 0,
      price: 160000,
      listPrice: 200000,
      manualPrice: null,
      sellingPrice: 144000,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        brandName: 'LG',
        brandId: '2000004',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/25/11/12/',
      productCategories: {
        '12': 'Cosmêticos',
      },
      quantity: 1,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://storecomponents.vteximg.com.br/arquivos/ids/155482-55-55/Frame-10.jpg?v=636793816835170000',
      detailUrl: '/everyday-necessaire/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [],
      offerings: [],
      priceTags: [
        {
          name:
            'discount@price-c9d0a34c-8a05-43ef-a9d3-88cd30e7f560#60f160d3-4626-42ab-ba98-415eb99129c6',
          value: -16000,
          rawValue: -160,
          isPercentual: false,
          identifier: 'c9d0a34c-8a05-43ef-a9d3-88cd30e7f560',
        },
      ],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
    },
    {
      uniqueId: 'E2742E68774E4A9D9121DA7D09287464',
      id: '31',
      productId: '14',
      productRefId: '',
      refId: '2863153',
      ean: '2863153',
      name: 'Top Fashion Eyeglasses 1',
      skuName: '1',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2020-12-17T14:27:08.5385871Z',
      tax: 0,
      price: 154000,
      listPrice: 190000,
      manualPrice: null,
      sellingPrice: 15400,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        brandName: 'Motorola',
        brandId: '2000007',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/25/32/',
      productCategories: {
        '25': 'Apparel & Accessoriess',
        '32': 'Eyeglasses',
      },
      quantity: 1,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://storecomponents.vteximg.com.br/arquivos/ids/155468-55-55/Frame-5.jpg?v=636793755542000000',
      detailUrl: '/fashion-eyeglasses/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [],
      offerings: [],
      priceTags: [
        {
          name:
            'discount@price-c9d0a34c-8a05-43ef-a9d3-88cd30e7f560#60f160d3-4626-42ab-ba98-415eb99129c6',
          value: -138600,
          rawValue: -1386,
          isPercentual: false,
          identifier: 'c9d0a34c-8a05-43ef-a9d3-88cd30e7f560',
        },
      ],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
    },
  ],
  selectableGifts: [],
  totalizers: [
    {
      id: 'Items',
      name: 'Items Total',
      value: 314000,
    },
    {
      id: 'Discounts',
      name: 'Discounts Total',
      value: -154600,
    },
  ],
  shippingData: {
    address: null,
    logisticsInfo: [
      {
        itemIndex: 0,
        selectedSla: null,
        selectedDeliveryChannel: 'delivery',
        addressId: null,
        slas: [],
        shipsTo: ['BRA', 'USA'],
        itemId: '20',
        deliveryChannels: [
          {
            id: 'delivery',
          },
        ],
      },
      {
        itemIndex: 1,
        selectedSla: null,
        selectedDeliveryChannel: 'delivery',
        addressId: null,
        slas: [],
        shipsTo: ['BRA', 'USA'],
        itemId: '31',
        deliveryChannels: [
          {
            id: 'delivery',
          },
        ],
      },
    ],
    selectedAddresses: [],
    availableAddresses: [],
    pickupPoints: [],
  },
  clientProfileData: null,
  paymentData: {
    installmentOptions: [
      {
        paymentSystem: '1',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 159400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 159400,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 159400,
                total: 159400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '2',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 159400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 159400,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 159400,
                total: 159400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 79700,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 79700,
                total: 159400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 53140,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 53140,
                total: 159400,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 39850,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 39850,
                total: 159400,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 31880,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 31880,
                total: 159400,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 26570,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 26570,
                total: 159400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '4',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 159400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 159400,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 159400,
                total: 159400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 79700,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 79700,
                total: 159400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 53140,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 53140,
                total: 159400,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 39850,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 39850,
                total: 159400,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 31880,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 31880,
                total: 159400,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 26570,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 26570,
                total: 159400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '6',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 159400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 159400,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 159400,
                total: 159400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '17',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 159400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 159400,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 159400,
                total: 159400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '64',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 159400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 159400,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 159400,
                total: 159400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 79700,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 79700,
                total: 159400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 53140,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 53140,
                total: 159400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '201',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 159400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 159400,
            total: 159400,
            sellerMerchantInstallments: [
              {
                id: 'STORECOMPONENTS',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 159400,
                total: 159400,
              },
            ],
          },
        ],
      },
    ],
    paymentSystems: [
      {
        id: 1,
        name: 'American Express',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^3[47][0-9]{13}$',
          mask: '9999 999999 99999',
          cardCodeRegex: '^[0-9]{4}$',
          cardCodeMask: '9999',
          weights: [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '1',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2019-12-24T14:14:31.4910714Z',
        availablePayments: null,
      },
      {
        id: 2,
        name: 'Visa',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^4[0-9]{15}$',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '2',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2019-12-24T14:14:31.4910714Z',
        availablePayments: null,
      },
      {
        id: 4,
        name: 'Mastercard',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex:
            '^((5(([1-2]|[4-5])[0-9]{8}|0((1|6)([0-9]{7}))|3(0(4((0|[2-9])[0-9]{5})|([0-3]|[5-9])[0-9]{6})|[1-9][0-9]{7})))|((508116)\\d{4,10})|((502121)\\d{4,10})|((589916)\\d{4,10})|(2[0-9]{15})|(67[0-9]{14})|(506387)\\d{4,10})',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '4',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2019-12-24T14:14:31.4910714Z',
        availablePayments: null,
      },
      {
        id: 17,
        name: 'Promissory',
        groupName: 'promissoryPaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '17',
        template: 'promissoryPaymentGroup-template',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2019-12-24T14:15:31.4910714Z',
        availablePayments: null,
      },
      {
        id: 201,
        name: 'Free',
        groupName: 'custom201PaymentGroupPaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '201',
        template: 'custom201PaymentGroupPaymentGroup-template',
        requiresDocument: false,
        isCustom: true,
        description: '',
        requiresAuthentication: false,
        dueDate: '2019-12-27T14:14:31.4910714Z',
        availablePayments: null,
      },
      {
        id: 64,
        name: 'Customer Credit',
        groupName: 'creditControlPaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '64',
        template: 'creditControlPaymentGroup-template',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2019-12-24T14:14:31.4910714Z',
        availablePayments: null,
      },
      {
        id: 6,
        name: 'Boleto Bancário',
        groupName: 'bankInvoicePaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '6',
        template: 'bankInvoicePaymentGroup-template',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2019-12-24T14:14:31.4910714Z',
        availablePayments: null,
      },
    ],
    payments: [],
    giftCards: [],
    giftCardMessages: [],
    availableAccounts: [],
    availableTokens: [],
  },
  marketingData: null,
  sellers: [
    {
      id: '1',
      name: 'VTEX',
      logo: '',
    },
  ],
  clientPreferencesData: {
    locale: 'en-US',
    optinNewsLetter: null,
  },
  commercialConditionData: null,
  storePreferencesData: {
    countryCode: 'USA',
    saveUserData: true,
    timeZone: 'Eastern Standard Time',
    currencyCode: 'USD',
    currencyLocale: 1116,
    currencySymbol: '$',
    currencyFormatInfo: {
      currencyDecimalDigits: 2,
      currencyDecimalSeparator: '.',
      currencyGroupSeparator: ',',
      currencyGroupSize: 3,
      startsWithCurrencySymbol: true,
    },
  },
  giftRegistryData: null,
  openTextField: null,
  invoiceData: null,
  customData: null,
  itemMetadata: {
    items: [
      {
        id: '20',
        seller: '1',
        name: 'Top Everyday Necessaire 100 RMS',
        skuName: '100 RMS',
        productId: '9',
        refId: '9812983',
        ean: '9812983',
        imageUrl:
          'http://storecomponents.vteximg.com.br/arquivos/ids/155482-55-55/Frame-10.jpg?v=636793816835170000',
        detailUrl: '/everyday-necessaire/p',
        assemblyOptions: [],
      },
      {
        id: '31',
        seller: '1',
        name: 'Top Fashion Eyeglasses 1',
        skuName: '1',
        productId: '14',
        refId: '2863153',
        ean: '2863153',
        imageUrl:
          'http://storecomponents.vteximg.com.br/arquivos/ids/155468-55-55/Frame-5.jpg?v=636793755542000000',
        detailUrl: '/fashion-eyeglasses/p',
        assemblyOptions: [],
      },
    ],
  },
  hooksData: null,
  ratesAndBenefitsData: {
    rateAndBenefitsIdentifiers: [
      {
        id: 'c9d0a34c-8a05-43ef-a9d3-88cd30e7f560',
        name: 'Porsche and Kawasaki',
        featured: true,
        description: null,
        matchedParameters: {
          'combo@Marketing': '20,31',
        },
        additionalInfo: null,
      },
    ],
    teaser: [],
  },
  subscriptionData: null,
  itemsOrdination: null,
}

export default orderForm
