import { Int } from '../primitive'

/* Count of Subscription by status */
export interface SubscriptionsStatusCount {
  active: Int
  paused: Int
  canceled: Int
}

/* Orders generated by subscription */
export interface SubscriptionsOrder {
  status: string
  /* SubscriptionId */
  orderGroup?: string,
  /* SubscriptionsOrder creation date */
  date: string
  /* DataInstanceId */
  dataInstanceId: string
  /* WorkflowId */
  workflowId:string
}

/* Count of SubscriptionsOrders by status */
export interface SubscriptionsOrdersStatusCount {
   triggered: Int
   inProcess: Int
   failure: Int
   success: Int
   expired: Int
   orderError: Int
   paymentError: Int
   skiped: Int
   successWithNoOrder: Int
   successWithPartialOrder: Int
}
