type Mutation {
  addItem(orderFormId: String, items: [OrderFormItemInput]): OrderForm
  cancelOrder(orderFormId: String, reason: String): Boolean
  updateItems(orderFormId: String, items: [OrderFormItemInput]): OrderForm
  updateProfile(id: String, fields: ProfileInput): OrderForm
  updateAddress(id: String, fields: AddressInput): OrderForm
  updateOrderFormProfile(orderFormId: String, fields: OrderFormProfileInput): OrderForm
  updateOrderFormShipping(orderFormId: String, address: OrderFormAddressInput): OrderForm
  updateOrderFormPayment(orderFormId: String,  payments: [OrderFormPaymentInput]): OrderForm
  updateOrderFormIgnoreProfile(orderFormId: String, ignoreProfileData: Boolean): OrderForm
  addOrderFormPaymentToken(orderFormId: String, paymentToken: OrderFormPaymentTokenInput): OrderForm
  setOrderFormCustomData(orderFormId: String, appId: String, field: String, value: String): OrderForm
  createAddress(fields: AddressInput): Profile
  deleteAddress(id: String): Boolean
  createPaymentSession: PaymentSession
  createPaymentTokens(sessionId: String, payments: [PaymentInput]): [PaymentToken]
  setPlaceholder(fields: PlaceholderInput): Boolean
}
