type Mutation {
  addItem(orderFormId: String, items: [OrderFormItemInput]): OrderForm
  cancelOrder(orderFormId: String, reason: String): Boolean
  updateItems(orderFormId: String, items: [OrderFormItemInput]): OrderForm
  updateProfile(orderFormId: String, fields: ProfileInput): OrderForm
  updateAddress(orderFormId: String, fields: AddressInput): OrderForm
  updateOrderFormProfile(orderFormId: String, fields: OrderFormProfileInput): OrderForm
  updateOrderFormShipping(orderFormId: String, fields: OrderFormAddressInput): OrderForm
  updateOrderFormIgnoreProfile(orderFormId: String, fields: IgnoreProfileInput): OrderForm
  createAddress(fields: AddressInput): Profile
  deleteAddress(id: String): Boolean
  setPlaceholder(fields: PlaceholderInput): Boolean
  createPayment(fields: PaymentInput): String
}
