type Query {
  product(slug: String): Product
  products(
    query: String = "",
    category: String = "",
    specificationFilters: [String],
    priceRange: String = "",
    collection: String = "",
    salesChannel: String = "",
    orderBy: String = "OrderByPriceDESC",
    from: Int = 0,
    to: Int = 9
  ): [Product]

  category(slug: String): Category
  categories: [Category]

  brand(slug: String): Brand

  shipping(skuId: String, postalCode: String): ShippingData

  orderForm: OrderForm
  orders: [Order]

  profile: Profile

  autocomplete(maxRows: Int = 12, searchTerm: String): Suggestions
}
